### PR TITLE
SVCPLAN-1333 Add ncsa/profile_session_log

### PR DESCRIPTION
**Pull request by bsper2**

### CODE REVIEW

**Review by billglick — APPROVED** [review]
Looks good.

**Comment by billglick** [comment]
I'd like to see this enabled in `asd-pup-control` and enabled in role `public_linux`.

**Comment by bsper2** [comment]
@billglick I can make a ticket to turn it on other places. Was a little confused by your comment, would you want it turned on just for `public_linux` in the `asd-pup-control` repo or want it on for all hosts in `asd-pup-control`

**Comment by billglick** [comment]
I was thinking 'just for `public_linux` in the `asd-pup-control` repo'. That is one of the few roles in asd-pup-control that random users SSH into.

**Comment by bsper2** [comment]
Gotcha makes sense, I've created https://jira.ncsa.illinois.edu/browse/SVCPLAN-4055 to turn that on

**Pull request merged**
